name: phgv2.4
channels:
  - conda-forge
  - bioconda
dependencies:
  - openjdk=21.0.7
  - python=3.12
  - pyyaml
  - anchorwave=1.2.5
  - bcftools
  - samtools
  - bedtools
  - agc=3.0
  - ropebwt3=3.8
  - minimap2=2.28
